dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11

# TODO split tests into mongo related & non mongo related. Run the former once.
env:
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 MINIO=2019-05-23T00-29-34Z ANT_TEST=test_quick_coverage WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.10 MINIO=2019-05-23T00-29-34Z ANT_TEST=test_quick_coverage WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.10 MINIO=2019-05-23T00-29-34Z ANT_TEST=test_quick_coverage WIRED_TIGER=true

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get -qq update
  - sudo apt-get install -y ant-optional
  - sudo apt-get install -y python3.6 python3-pip
  - pyenv local 3.6
  - python --version
  - pip3 --version
  - pip3 install sphinx
  - pip3 install jsonrpcbase==0.2.0
  - pip3 install configparser==4.0.2
  - pip3 install pymongo==3.9.0
  - pip3 install cachetools==3.1.1
  - pip3 install uwsgi==2.0.18

install:
  - export HOMEDIR=`pwd`
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/

  - export HS_COMMIT=aae2f70120e75d2ccccab1b1c01dbb9e8327eee8
  - export LOG_COMMIT=b549c557e3c519e0a55eadf7863a93db25cd6806
  - git clone https://github.com/kbase/handle_service2.git
  - cd handle_service2/
  - git checkout $HS_COMMIT
  - sudo chmod -R 777 .
  - cd lib/
  - mkdir biokbase
  - cd biokbase/
  - wget https://raw.githubusercontent.com/kbase/sdkbase2/$LOG_COMMIT/log.py
  - cd ..
  - export HSDIR=`pwd`
  - cd $HOMEDIR

script:
  # set up minio
  - cd ..
  - wget https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.$MINIO -O minio
  - chmod a+x minio
  - export MINIOD=`pwd`/minio
  - cd -

  # set up mongo
  - cd ..
  - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
  - tar xfz $MONGODB_VER.tgz
  - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
  - cd -

   # set up config file
  - export SHOCKEXE=`pwd`/shock_builds/kbase_fork/160815_e9f0e1618e265042bf5cb96429995b5e6ec0a06a/shock-server
  - cp -n test.cfg.example test.cfg
  - sed -i "s#^test.temp.dir =.*#test.temp.dir=temp_test_dir#" test.cfg
  - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
  - sed -i "s#^test.minio.exe.*#test.minio.exe=$MINIOD#" test.cfg
  - sed -i "s#^test.mongo.wired_tiger.*#test.mongo.wired_tiger=$WIRED_TIGER#" test.cfg
  - sed -i "s#^test.jars.dir.*#test.jars.dir=$JARSDIR#" test.cfg
  - sed -i "s#^test.shock.version.*#test.shock.version=0.9.6#" test.cfg
  - sed -i "s#^test.shock.exe.*#test.shock.exe=$SHOCKEXE#" test.cfg
  - sed -i "s#^test.handleservice.dir.*#test.handleservice.dir=$HSDIR#" test.cfg
  - cat test.cfg
 
  # run tests
  - ant javadoc
  - ant $ANT_TEST

after_success:
  - ls test-reports
  - bash <(curl -s https://codecov.io/bash) -f test-reports/coverage-report.xml

