dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ant-optional
  - sudo pip install sphinx
install:
  - cd ..
  - git clone https://github.com/kbase/jars
  - cd -

script:
  - ant javadoc
  - ant compile
  
